# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/gig_ethernet_pcs_pma_basex_156_25.xci
# IP: The module: 'gig_ethernet_pcs_pma_basex_156_25' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/ip_0/gig_ethernet_pcs_pma_basex_156_25_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_basex_156_25_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_basex_156_25_gt} -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/ip_0/synth/gig_ethernet_pcs_pma_basex_156_25_gt_ooc.xdc

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/ip_0/synth/gig_ethernet_pcs_pma_basex_156_25_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_basex_156_25_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_basex_156_25_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/gig_ethernet_pcs_pma_basex_156_25_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_basex_156_25'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/synth/gig_ethernet_pcs_pma_basex_156_25.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_basex_156_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/synth/gig_ethernet_pcs_pma_basex_156_25_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_basex_156_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/synth/gig_ethernet_pcs_pma_basex_156_25_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_basex_156_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/gig_ethernet_pcs_pma_basex_156_25.xci
# IP: The module: 'gig_ethernet_pcs_pma_basex_156_25' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/ip_0/gig_ethernet_pcs_pma_basex_156_25_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_basex_156_25_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_basex_156_25_gt} -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/ip_0/synth/gig_ethernet_pcs_pma_basex_156_25_gt_ooc.xdc

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/ip_0/synth/gig_ethernet_pcs_pma_basex_156_25_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_basex_156_25_gt || ORIG_REF_NAME==gig_ethernet_pcs_pma_basex_156_25_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/gig_ethernet_pcs_pma_basex_156_25_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_basex_156_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/synth/gig_ethernet_pcs_pma_basex_156_25.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_basex_156_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/synth/gig_ethernet_pcs_pma_basex_156_25_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_basex_156_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/synth/gig_ethernet_pcs_pma_basex_156_25_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_basex_156_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
