# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.cache/wt [current_project]
set_property parent.project_path C:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_reg_types.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_peephole_ram.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ram.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ctrlreg_v.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_reg_v.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_util/firmware/hdl/ipbus_decode_ipbus_example.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_fabric_sel.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_util/firmware/hdl/ipbus_example.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_package.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_eth/firmware/hdl/emac_hostbus_decl.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_eth/firmware/hdl/eth_us_1000basex.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_trans_decl.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_cfg.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_sm.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_if.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/trans_arb.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_txtransactor_if_simple.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_tx_mux.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_status_buffer.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxtransactor_if_simple.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxram_shim.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxram_mux.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rarp_block.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_packet_parser.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_ipaddr_block.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram_tx.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram_rx.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_do_rx_reset.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_clock_crossing_if.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_byte_sum.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_status.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_resend.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_ping.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_payload.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_arp.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_buffer_selector.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_if_flat.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_ctrl.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_util/firmware/hdl/led_stretcher.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_util/firmware/hdl/ipbus_clock_div.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/components/ipbus_util/firmware/hdl/clocks_us_serdes.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/boards/kcu105/base_fw/kcu105_basex/synth/firmware/hdl/kcu105_basex_infra.vhd
  C:/Users/santi/OneDrive/PhD/myarea/src/ipbus-firmware/boards/kcu105/base_fw/kcu105_basex/synth/firmware/hdl/kcu105_basex.vhd
}
read_ip -quiet C:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/gig_ethernet_pcs_pma_basex_156_25.xci
set_property used_in_implementation false [get_files -all c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/ip_0/synth/gig_ethernet_pcs_pma_basex_156_25_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/ip_0/synth/gig_ethernet_pcs_pma_basex_156_25_gt.xdc]
set_property used_in_implementation false [get_files -all c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/gig_ethernet_pcs_pma_basex_156_25_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/synth/gig_ethernet_pcs_pma_basex_156_25.xdc]
set_property used_in_implementation false [get_files -all c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/synth/gig_ethernet_pcs_pma_basex_156_25_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/gig_ethernet_pcs_pma_basex_156_25/synth/gig_ethernet_pcs_pma_basex_156_25_ooc.xdc]

read_ip -quiet C:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/temac_gbe_v9_0.xci
set_property used_in_implementation false [get_files -all c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0_clocks.xdc]

read_ip -quiet c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/santi/OneDrive/PhD/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top top -part xcku040-ffva1156-2-e -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
