# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/temac_gbe_v9_0.xci
# IP: The module: 'temac_gbe_v9_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/temac_gbe_v9_0.xci
# IP: The module: 'temac_gbe_v9_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lucas/Downloads/myarea/proj/kcu105_basex/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
